# Site settings
author: James Batsell
title: Dreadheaddreamz
header-img: img/home-bg.png
email: jamesbatsell05@gmail.com
copyright_name: James Batsell
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my world
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: Dreadheaddreamz
github_username:  dreadheaddreamz

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
